# Generated by Django 4.2.6 on 2023-10-24 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_lastname', models.CharField(max_length=100)),
                ('admin_age', models.IntegerField()),
                ('admin_phone', models.CharField(max_length=100, unique=True)),
                ('admin_pass', models.CharField(max_length=8, unique=True)),
                ('admin_poll', models.CharField(blank=True, choices=[('WOMEN', 'WOMEN'), ('MAN', 'MAN')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_lastname', models.CharField(max_length=100)),
                ('stu_age', models.IntegerField()),
                ('stu_phone', models.CharField(max_length=100, unique=True)),
                ('stu_parents_name', models.CharField(max_length=100)),
                ('stu_parents_phone', models.CharField(max_length=100, unique=True)),
                ('stu_id', models.CharField(max_length=100, unique=True)),
                ('stu_pass', models.CharField(max_length=8, unique=True)),
                ('stu_category', models.CharField(blank=True, choices=[('FRONTEND', 'FRONTEND'), ('BACKEND', 'BACKEND')], max_length=100)),
                ('stu_roll', models.CharField(blank=True, choices=[('GAMER', 'GAMER'), ('HACKER', 'HACKER'), ('CODER', 'CODER')], max_length=100)),
                ('result', models.IntegerField(null=True)),
                ('stu_coin', models.IntegerField(null=True)),
                ('is_have', models.BooleanField(default=False)),
                ('stu_paymant', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teach_name', models.CharField(max_length=100)),
                ('teach_lastname', models.CharField(max_length=100)),
                ('teach_age', models.IntegerField()),
                ('teach_phone', models.CharField(max_length=100, unique=True)),
                ('teach_pass', models.CharField(max_length=8, unique=True)),
                ('teach_email', models.EmailField(max_length=254)),
                ('teach_level', models.CharField(blank=True, choices=[('JUNIOR', 'JUINOR'), ('MIDDLE', 'MIDDLE'), ('SENIOR', 'SERIOR')], max_length=100)),
                ('tech_job', models.CharField(blank=True, choices=[('TUTOR', 'TUTOR'), ('INCTRUCTOR', 'INCTRUCTOR'), ('MENTOR', 'MENTOR')], max_length=100)),
                ('teach_category', models.CharField(blank=True, choices=[('FRONTEND', 'FRONTEND'), ('BACKEND', 'BACKEND')], max_length=100)),
                ('teach_poll', models.CharField(blank=True, choices=[('WOMEN', 'WOMEN'), ('MAN', 'MAN')], max_length=100)),
                ('result', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('group_time', models.TimeField()),
                ('group_category', models.CharField(blank=True, choices=[('FRONTEND', 'FRONTEND'), ('BACKEND', 'BACKEND')], max_length=100)),
                ('group_age', models.CharField(choices=[('YOUNG', 'YOUNG'), ('OLDER', 'OLDER')], max_length=255)),
                ('group_students', models.ManyToManyField(to='Schsystem.students')),
                ('group_teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schsystem.teachers')),
            ],
        ),
    ]
